**Documents Links**

[[Documentation](https://pandas.pydata.org/)]

[dataset](https://github.com/mwanyumba7/GHDemo/tree/main/Tableau/Data)

**Libraries**

In [1]:
import pandas as pd

In [2]:
summer_olympics = pd.read_csv("C:\\Users\\iruehtniwde\\Documents\\data-science\\python-data-analysis\\class-activity\\summer2016.csv")

In [7]:
type(summer_olympics)

pandas.DataFrame

In [3]:
summer_olympics.info()

<class 'pandas.DataFrame'>
RangeIndex: 2014 entries, 0 to 2013
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2014 non-null   int64
 1   ID          2014 non-null   int64
 2   Name        2014 non-null   str
 3   Sex         2014 non-null   str
 4   Age         2014 non-null   float64
 5   Height      2014 non-null   float64
 6   Weight      2014 non-null   float64
 7   Team        2014 non-null   str
 8   NOC         2014 non-null   str
 9   Games       2014 non-null   str
 10  Year        2014 non-null   int64
 11  Season      2014 non-null   str
 12  City        2014 non-null   str
 13  Sport       2014 non-null   str
 14  Event       2014 non-null   str
 15  Medal       2014 non-null   str
dtypes: float64(3), int64(3), str(10)
memory usage: 251.9 KB

In [6]:
summer_olympics.describe() #calculates summary statistics for numeric columns in the DataFrame.

,Unnamed: 0,ID,Age,Height,Weight,Year
count,2014.000000,2014.000000,2014.000000,2014.000000,2014.00000,2014.0
mean,138388.323237,69652.522344,26.337637,178.373386,73.96574,2016.0
std,79196.324065,39486.626421,5.143563,11.882251,16.21923,0.0
min,158.000000,62.000000,15.000000,140.000000,33.00000,2016.0
25%,67859.250000,34682.500000,23.000000,170.000000,63.00000,2016.0
50%,141767.500000,71119.000000,26.000000,178.000000,72.00000,2016.0
75%,206763.750000,103776.750000,29.000000,186.000000,83.75000,2016.0
max,271019.000000,135525.000000,58.000000,215.000000,160.00000,2016.0

In [32]:
summer_olympics.values

array([[62, 'Giovanni Abagnale', 'M', ..., 'Rowing',
        "Rowing Men's Coxless Pairs", 'Bronze'],
       [65, 'Patimat Abakarova', 'F', ..., 'Taekwondo',
        "Taekwondo Women's Flyweight", 'Bronze'],
       [73, 'Luc Abalo', 'M', ..., 'Handball', "Handball Men's Handball",
        'Silver'],
       ...,
       [135205, 'Shakhobiddin Shokirovich Zoirov', 'M', ..., 'Boxing',
        "Boxing Men's Flyweight", 'Gold'],
       [135245, 'Milenko Zori', 'M', ..., 'Canoeing',
        "Canoeing Men's Kayak Doubles, 1,000 metres", 'Silver'],
       [135525, 'Martin Zwicker', 'M', ..., 'Hockey',
        "Hockey Men's Hockey", 'Bronze']], shape=(2014, 15), dtype=object)

**Cleaning data**

- In this step we perform the following: 
    - Checking for missing values
    - Dropping Columns we do not need
    - Checking for Duplicates
    - Checking for outliers

In [35]:
#checking for missing values in the DataFrame
summer_olympics.isna().sum()

ID        0
Name      0
Sex       0
Age       0
Height    0
Weight    0
Team      0
NOC       0
Games     0
Year      0
Season    0
City      0
Sport     0
Event     0
Medal     0
dtype: int64

In [36]:
summer_olympics.columns #checks for column names in the DataFrame

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='str')

In [37]:
type(summer_olympics)

pandas.DataFrame

In [41]:
summer_olympics.drop("Unnamed: 0", axis=1) #removing the "Unnamed: 0" column from the DataFrame

KeyError: "['Unnamed: 0'] not found in axis"

In [40]:
summer_olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,62,Giovanni Abagnale,M,21.0,198.0,90.0,Italy,ITA,2016 Summer,2016,Summer,Rio de Janeiro,Rowing,Rowing Men's Coxless Pairs,Bronze
1,65,Patimat Abakarova,F,21.0,165.0,49.0,Azerbaijan,AZE,2016 Summer,2016,Summer,Rio de Janeiro,Taekwondo,Taekwondo Women's Flyweight,Bronze
2,73,Luc Abalo,M,31.0,182.0,86.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Men's Handball,Silver
3,250,Saeid Morad Abdevali,M,26.0,170.0,80.0,Iran,IRI,2016 Summer,2016,Summer,Rio de Janeiro,Wrestling,"Wrestling Men's Middleweight, Greco-Roman",Bronze
4,455,Denis Mikhaylovich Ablyazin,M,24.0,161.0,62.0,Russia,RUS,2016 Summer,2016,Summer,Rio de Janeiro,Gymnastics,Gymnastics Men's Team All-Around,Silver